/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-01-17 02:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.actionTag.example2.plan;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/actionTag/example2/plan/../include/footer.jsp", Long.valueOf(1484620579864L));
    _jspx_dependants.put("/actionTag/example2/plan/../include/header.jsp", Long.valueOf(1484620579865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- template.jsp 파일명 -->    \r\n");

   String pagefile=request.getParameter("page");
   if(pagefile==null){
	   pagefile="plan01";  //pagefile이 없으면 galler01로 지정
   }   

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset=\"UTF-8\">\r\n");
      out.write("      <script> document.documentElement.className = 'js'; </script> \r\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("      <link rel=\"shortcut icon\" href=\"/favicon.ico\">\r\n");
      out.write("      <link rel=\"apple-touch-icon\" href=\"/apple-touch-icon.png\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../css/960gs.css\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../css/typo.css\" />            \r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../css/style.css\" />\r\n");
      out.write("      <link rel=\"stylesheet\" media=\"handheld\" href=\"css/handheld.css?v=1\">\r\n");
      out.write("\r\n");
      out.write("      <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("      <script src=\"../js/jquery.js\"></script>\r\n");
      out.write("      <script src=\"../js/function.js\"></script>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("\t  <script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t  <script src=\"//code.jquery.com/ui/1.10.4/jquery-ui.js\"></script>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- Slide Links -->\r\n");
      out.write("\t  <script src=\"../js/sl.js\"></script>\r\n");
      out.write("\t  <script src=\"../js/jquery2.js\"></script>\r\n");
      out.write("\t  <!-- standalone page styling (can be removed) -->\r\n");
      out.write("\t  <!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/standalo.css\"/> -->\t\r\n");
      out.write("\t  <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/slide.css\"/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- Board Links -->\r\n");
      out.write("\t  <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/board.css\"/>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <script src=\"../js/datacheck.js\"> </script>\t\r\n");
      out.write("\r\n");
      out.write("      <title> Life Design </title>\r\n");
      out.write("\r\n");
      out.write("   </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!------------------ HEADER 영역 시작 ------------------> \r\n");
      out.write("  \r\n");
      out.write("   <header class=\"container_24\">\r\n");
      out.write("      <h1> <a href=\"../index.jsp\" class=\"logo\"> Life Design </a> </h1>\r\n");
      out.write("      <nav class=\"grid_17\">\r\n");
      out.write("         <ul>\r\n");
      out.write("         \t<li>\r\n");
      out.write("               <a href=\"#\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\">About</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\">Planner</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\">Calculator</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\" onclick=\"alert('로그인 후 이용해주세요.');\">Download</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\">Board</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\">Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <section>\r\n");
      out.write("         <ul id=\"Social\">\r\n");
      out.write("            <li>\r\n");
      out.write("               <a target=\"_blank\" href=\"https://www.facebook.com/pages/Life-Design/274638092705934?skip_nax_wizard=true#!/pages/Life-Design/274638092705934\">\r\n");
      out.write("                  <img src=\"../img/icons/facebook.png\" alt=\"Facebook\" />\r\n");
      out.write("               </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\" onclick=\"alert('준비중 입니다.');\">\r\n");
      out.write("                  <img src=\"../img/icons/dribble.png\" alt=\"Dribble\" />\r\n");
      out.write("               </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\" onclick=\"alert('준비중 입니다.');\">\r\n");
      out.write("                  <img src=\"../img/icons/twitter.png\" alt=\"Twitter\" />\r\n");
      out.write("               </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"#\" onclick=\"alert('준비중 입니다.');\">\r\n");
      out.write("                  <img src=\"../img/icons/flickr.png\" alt=\"Flickr\" />\r\n");
      out.write("               </a>\r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("   </header>\r\n");
      out.write("   \r\n");
      out.write("<!------------------ HEADER 영역 끝 ------------------>    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"main\" class=\"container_24\">\r\n");
      out.write("   <table style=\"width: 960px; text-align:center; margin-bottom: 50px;\">\r\n");
      out.write("       \r\n");
      out.write("      <tr class=\"test\"> <!-- 2행 -> 본문 영역 -->\r\n");
      out.write("         <td width=\"25%\" align=\"left\" height=\"200\" valign=\"top\">   <!-- 왼쪽 부분 -->\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left.jsp", out, false);
      out.write("\r\n");
      out.write("         </td>\r\n");
      out.write("         <td colspan=\"2\" align=\"justify\" style=\"padding: 0 20px;\"> <!-- 오른쪽 부분 -->\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, pagefile+".jsp", out, false);
      out.write("\r\n");
      out.write("         </td>   \r\n");
      out.write("      </tr>   \r\n");
      out.write(" \r\n");
      out.write("   </table>\r\n");
      out.write("</div>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!------------------ FOOTER 영역 시작 ------------------>\r\n");
      out.write("\r\n");
      out.write("   <div id=\"footer-wrap\">\r\n");
      out.write("      <footer class=\"container_24\">\r\n");
      out.write("\t      <section></section>\r\n");
      out.write("      </footer>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <div id=\"infoFooter\">\r\n");
      out.write("   \t<footer class=\"container_24\">\r\n");
      out.write("      <p><img style=\"position:relative; float:left; top:10px; width:90px;\" src=\"../img/ci.PNG\" />&nbsp;  Copyright CLT Money Planner -- All Rights Reserved</p>\r\n");
      out.write("      <nav>\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../index.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../about/about.jsp\">About</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../plan/plan.jsp\">Planner</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../calc/calc1.jsp\">Calculator</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../index.jsp\" onclick=\"alert('로그인 후 이용해주세요.');\">Download</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../board_list1.do\">Board</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("               <a href=\"../contact/contact.jsp\">Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("<!------------------ FOOTER 영역 끝 ------------------>      \r\n");
      out.write("      \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
