/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-01-17 02:37:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.actionTag.example2.plan;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class plan03_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\">사회초년생 기초 재무가이드</h1>\r\n");
      out.write("<h4 align=\"center\">무작정 저축? 돈 모으는 선택을 하라</h4>\r\n");
      out.write("<br><br>\r\n");
      out.write("<div style=\"border-left:3px solid gray; padding-left:10px; margin-left:10px;\">\r\n");
      out.write("그대, 좌절했는가?<br>\r\n");
      out.write("친구들은 승승장구하고 있는데, 그대만 잉여의 나날을 보내고 있는가?<br>\r\n");
      out.write("(중략)<br>\r\n");
      out.write("20세는 오전 6시, 29세는 오전 8시 42분이다.<br>\r\n");
      out.write("평균수명이 늘어나면 그대의 인생시각은 더 여유로워질 확률이 높다.<br><br>\r\n");
      out.write("<span style=\"color:brown;\">-[아프니까 청춘이다] 중에서..</span>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<img src=image/k1.PNG style=\"float:right; padding-left:20px\">\r\n");
      out.write("수많은 청춘의 가슴을 울린 '아프니깐 청춘이다'의 한 부분이다. \r\n");
      out.write("책의 내용처럼, 인생을 시간으로 따져보면 20~30대는 하루 중 오전에 해당하고 평균수명 또한 계속 늘고 있다. \r\n");
      out.write("하지만 이 때문에 인생시각이 여유로워질 확률은 높지 않을 것이다. \r\n");
      out.write("평균수명의 연장과 동시에 '고 연령층'은 더 빠른 속도로 증가할 것이고, 앞으로 2030세대가 부담해야 할 세금도 그만큼 더 많아지게 된다. \r\n");
      out.write("게다가 일자리 부족현상과 정년퇴임기간 단축까지 생각한다면, 온갖 '돈 문제'로 괴로워지는 게 오늘날 젊은 세대들의 현실과 미래이기 때문. \r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("'돈'이란 알고 모르느냐에 따라 인생에 도움이 될 수도 해가 될 수도 있다. \r\n");
      out.write("잘 벌기만 하는 사람은 잘 모으는 사람을 이길 수 없고, 무작정 모으기만 하는 사람은 제대로 알고 관리하는 사람을 결코 이길 수 없다. \r\n");
      out.write("2030세대가 꼭 알아야 할 돈 이야기에 귀 기울여 보자. \r\n");
      out.write("<br><br>\r\n");
      out.write("<hr>\r\n");
      out.write("<h4 align=\"center\">목표가 명확하면 더 쉬워진다</h4>\r\n");
      out.write("<hr><br><br>\r\n");
      out.write("목표가 명확히 세워지지 않은 상태에서는 저축이나 투자할 때, 1년 만기로 해야 할지, 아니면 3년 만기로 해야 할 지, 펀드에 가입할지, 적금에 들지 판단이 서지 않는다. \r\n");
      out.write("결국, 잘못된 판단으로 목적이 모호한 상품에 가입했다가 만기를 채우지 못한 채 중도에 해약하게 되는 경우도 다반사다. \r\n");
      out.write("가령, 1년 안에 꼭 써야 할 자금이 있는데도 1년짜리 저축상품이 아닌 장기상품(적립식펀드, 저축보험 등)에 가입한다면 돈이 필요해질 때 큰 곤란을 겪게 될 것이다. \r\n");
      out.write("게다가 장기상품을 중도해약하면 약관에 정해진 \"해약공제금\"으로 납입한 원금을 보장받지 못할 수도 있기 때문이다. \r\n");
      out.write("따라서 어떤 목적으로 얼마 동안 돈을 모아야 하는지 재무목표를 명확하게 설정하는 것이 가장 중요한 시기임을 명심해두자.\r\n");
      out.write("<br><br>\r\n");
      out.write("<div style=\"border: 1px solid gray; padding: 20px\">\r\n");
      out.write("<b>[2030 포트폴리오 만들기 3가지 Tip]</b><br>\r\n");
      out.write("1. 월 소득과 전체적인 지출사항, 자동이체일 등 재무사항을 정확하게 기록한다.<br>\r\n");
      out.write("2. 변동사항에 대비해 월 소득의 5%(최소)는 수시입출식 계좌에 적립해둔다.<br>\r\n");
      out.write("3. 내 투자성향을 파악하고, 반드시 목표에 맞게 분류하여 저축이나 투자한다.<br>\r\n");
      out.write("</div><br><br>\r\n");
      out.write("<hr>\r\n");
      out.write("<h4 align=\"center\">아는 만큼 수익 낼 수 있다</h4>\r\n");
      out.write("<hr><br><br>\r\n");
      out.write("<img src=image/k2.PNG style=\"float:right; padding: 0 10px 20px 20px;\">\r\n");
      out.write("재무목표를 세웠다면 금융상품을 선택해 스스로 관리할 수 있는 경로를 만들어야 한다. \r\n");
      out.write("하지만 요즘처럼 금리가 크게 하락할 때는 예/적금과 같은 통상적인 금융상품만으로 재테크를 하기엔 아쉽다는 생각이 들 수 밖에 없다. \r\n");
      out.write("적금에 모두 넣자니 이자가 턱없이 낮고 펀드에 몰아서 투자하자니 불안한 것. \r\n");
      out.write("그렇다면 방법은 없는 걸까? \r\n");
      out.write("다음의 다양한 금융상품 중에서 내게 맞는 금융상품은 어떤 게 있는지 살펴보자. \r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("<div style=\"border: 1px solid gray; padding: 20px\">\r\n");
      out.write("<b>[꼭 알아야 할 금융상품 8가지]</b><br>\r\n");
      out.write("<b>1. 정기적금 :</b> 약정 기간, 금액을 적립해 정해진 이자를 받는 상품<br>\r\n");
      out.write("투자경험이 없고, 안정적인 성향이라면 정기적금을 활용해 1년 단위로 목돈을 만드는 것을 추천한다. \r\n");
      out.write("1년마다 안정적으로 목돈을 만든 후, 만기가 되었을 때 정기예금이나 특판예금(ELS), 채권투자 등으로 재투자 하는 것도 좋은 방안이 될 수 있다. \r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>2. 적립식 펀드 :</b>  약정기간, 금액 또는 자유롭게 적립해 투자수익에 따라 수익을 배분받는 상품<br>\r\n");
      out.write("보다 높은 수익을 기대할 수 있고, 주가의 변동성을 고려해 단기 수익을 노리는 것보다는 장기적인 측면으로 투자하는 것이 현명하다. \r\n");
      out.write("투자성향에 따라 주식형/혼합형/채권형 펀드의 선택이 가능하다. \r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>3. 저축보험 :</b> 약정기간, 금액을 적립해 투자수익 또는 변동금리에 따라 이자(수익)를 받는 상품<br>\r\n");
      out.write("짧게는 3년 만기, 5년 만기의 저축보험이 있으며 공시이율을 연 복리로 계산해 이자를 만기에 원금과 함께 받는다. \r\n");
      out.write("(예금자보호) 변액보험의 경우, 가입 시 설정한 각 펀드에 투자되며 분산투자 효과가 있고 펀드변경이 가능하다.\r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>4. 정기예금 :</b> 일정금액의 목돈을 한 번에 예치해 약정한 만기에 이자를 받는 상품<br>\r\n");
      out.write("예금자보호가 되며, 안정적인 성향일 경우에 \"목돈 굴리기\" 용도로 적합하다.\r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>5. 특판예금(ELS) :</b> 발행되는 상품에 목돈을 예치해 정해진 투자옵션에 따라 수익을 배분받는 상품<br>\r\n");
      out.write("은행과 증권사에서 취급하는 주가와 연계되는 거치형 상품으로, 100만 원 단위로 투자할 수 있다. \r\n");
      out.write("매 해당 평가일에 기준이 적합하면 정해진 옵션에 따라 원금과 이자를 조기에 받을 수 있으며 주가가 변동되더라도 원금을 보장해주는 상품도 출시되고 있다. \r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>6. 수시입출식 통장 :</b> 금액과 기간에 상관없이 일 단위로 책정하여 이자를 받는 상품<br>\r\n");
      out.write("주로 증권사와 종금사에서 판매되던 수시입출식 계좌(통장)는, 최근 들어 시중은행에도 출시되고 있다. \r\n");
      out.write("정기예금과는 달리, 1일 단위로 평가되어 이자를 받을 수 있으며 목돈을 짧은 기간 동안 잠시 예치해 두거나 생활자금 또는 비상자금 계좌로 활용하면 보통예금에 예치하는 것보다 많은 수익(이자)을 얻을 수 있다. \r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>7. 연금보험/펀드 :</b> 약정 기간. 금액으로 적립해 약정한 나이에 연금으로 받는 상품<br>\r\n");
      out.write("사회초년생을 때 무리한 금액으로 연금상품에 가입했다가 중도에 해약을 해야하는 경우가 적지 않다. \r\n");
      out.write("예를 들어, 연금저축(펀드) 소득공제의 연간한도액인 400만 원에 대한 혜택을 받기 위해 약 33만 4,000원을 월 불입액으로 가입했다가 중도에 깨고 '해지가산세'와 더불어 '해약공제금'까지 모두 한 번에 물게 되는 것이다. \r\n");
      out.write("이 상품은 유지기간이 가장 긴 상품인 만큼, 반드시 단기목표를 함께 고려해야 한다. \r\n");
      out.write("소득공제에 혜택이 있는 상품으로 가입할 때는 가입금액을 적절하게 설정한 뒤 연말성과급이나 분기별 보너스 등을 추가로 납입해 부족한 소득공제 혜택을 채우는 것도 나쁘지 않다. \r\n");
      out.write("또한, 장기적인 측면을 고려해본다면 일반연금이나 변액연금을 통해 비과세혜택을 노리는 것도 좋은 방안이 될 수 있다. \r\n");
      out.write("<hr style=\"border-style: dotted;\">\r\n");
      out.write("<b>8. 기타 :</b> 청약저축 주택청약을 위해 무주택세대주나 실 수요자를 위한 적립식 저축상품<br>\r\n");
      out.write("전 금융기간을 통틀어 1인 1계좌에만 가입할 수 있으며 청약종합저축과 청약저축은 연간 불입액의 40%까지 소득공제혜택이 있다. \r\n");
      out.write("청약 1순위 자격을 얻으려면 가입 후 2년이 지나야하며 중간에 불입이 미뤄지면 그 기간만큼 1순위 자격이 될 수 있는 기간도 미뤄진다는 것을 꼭 알아두자.\r\n");
      out.write("</div> \r\n");
      out.write("<br><br>\r\n");
      out.write("<hr><h4 align=\"center\">지속적인 훈련과정이 필요하다</h4>\r\n");
      out.write("<hr><br><br>\r\n");
      out.write("수년 전 재테크 열풍이 불었던 때가 있었다. \r\n");
      out.write("사회초년생을 비롯한 많은 직장인이 재테크 서적과 인터넷 정보를 수집해가면서 마치 자신이 금융전문가가 된 것 마냥 서로 펀드를 추천했다. \r\n");
      out.write("개중에는 믿을만한 정보란 말에 속아 주식에 투자했다가 결혼자금 등 목돈을 몽땅 날린 경우도 적잖게 발생했다. \r\n");
      out.write("심한 경우엔 가입했던 펀드에 대한 소송까지도 이어졌다. \r\n");
      out.write("<br><br>\r\n");
      out.write("성공적인 돈 모으기란 다양한 지식과 고수익만 노리는 투자가 아니다. \r\n");
      out.write("쏟아지는 정보의 홍수 속에서 재테크에 대한 일반인들의 지식은 풍부해졌고, 금융사들은 전문가가 된 고객을 유치하기 위해 수수료 경쟁을 벌이고 있다. \r\n");
      out.write("하지만 정작 돈 모으는데 가장 중요한 '마음가짐'과 '지키기 위한 저축과 투자'는 강요하지 않는다. \r\n");
      out.write("<br><br>\r\n");
      out.write("프로야구 선수들은, 매년 정규시즌에 벌어지는 4월부터 10월까지의 경기를 위해 가을부터 이듬해의 봄까지 피나는 연습과 훈련을 반복한다. \r\n");
      out.write("특히 연습과 훈련을 게일리하지 않은 선수는 불필요한 부상을 당하지 않는다고 한다. \r\n");
      out.write("재테크도 마찬가지다. \r\n");
      out.write("반드시 철저한 계획과 훈련과정이 필요한 것이다. \r\n");
      out.write("<br><br>\r\n");
      out.write("사회초년생이라면, 위험을 무릅쓰면서 수익만 좇는 災테크보다 자신의 재무목표를 유지하면서 건강하게 잘 지킬 수 있는 財테크를 하는 게 무엇보다 중요하단 걸 명심하라! \r\n");
      out.write("<br><br>\r\n");
      out.write("<hr>\r\n");
      out.write("<b>글</b> 김형태<br>\r\n");
      out.write("<b>기획</b> 정아람 기자<br>\r\n");
      out.write("<b>발행</b> (주)이패스코리아<br>\r\n");
      out.write("<b>제공</b> 머니플러스<br><br>\r\n");
      out.write("<hr>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
