/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-01-23 02:34:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member_005fver2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- member/join_form.jsp -->    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>회원가입 폼</title>\r\n");
      out.write("<!-- 제이쿼리 라이브러리 링크 -->\r\n");
      out.write("<script src=\"../js/jquery-3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  $(function(){ \r\n");
      out.write("\t// 현재 웹문서가 브라우저로 로딩될 때 자동 호출 무명함수\r\n");
      out.write("\t$(\"#submit\").click(function(){\r\n");
      out.write("\t\tif($(\"#id\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"id를 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#pass\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"pass를 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#pass\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#name\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"name를 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#name\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#sel_mail\").change(function(obj){ // 셀렉트 상자\r\n");
      out.write("\t   // 1. 셀렉트 상자에서 선택한 도메인을 변수에 저장\r\n");
      out.write("\t   var mailValue = $(obj.target).val(); \r\n");
      out.write("\t   // 2. email2 텍스트 상자에 도메인 표시\r\n");
      out.write("\t   $(\"#email2\").attr(\"value\",mailValue);\t   \r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#reset\").click(function(){ // 다시작성\r\n");
      out.write("\t\t$(\"#email2\").attr(\"value\",\"\");\r\n");
      out.write("\t\t$(\"#id\").focus();\r\n");
      out.write("\t});\r\n");
      out.write("  }); \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <form name=\"join\" action=\"../join.do\" \r\n");
      out.write("       method=\"post\">\r\n");
      out.write("    <table border=\"1\" align=\"center\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th colspan=\"2\"> <h3>회원가입 페이지 </h3></th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th> 아이디 </th>\r\n");
      out.write("         <td  align=\"center\"> <input name=\"id\" id=\"id\"/> </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th> 비밀번호 </th>\r\n");
      out.write("         <td  align=\"center\"> <input type=\"password\" name=\"pass\" \r\n");
      out.write("               id=\"pass\"/> </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th> 이름 </th>\r\n");
      out.write("         <td  align=\"center\"> <input name=\"name\" id=\"name\"/> </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th> 주민번호 </th>\r\n");
      out.write("         <td align=\"center\"> \r\n");
      out.write("          <input name=\"jumin1\" size=\"6\" maxlength=\"6\" id=\"jumin1\"/>-\r\n");
      out.write("          <input name=\"jumin2\" size=\"7\" maxlength=\"7\" id=\"jumin2\"/>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th> 이메일 </th>\r\n");
      out.write("        <td> \r\n");
      out.write("          <input name=\"email1\" id=\"email1\" size=\"10\">@\r\n");
      out.write("          <input name=\"email2\" id=\"email2\" size=\"10\">\r\n");
      out.write("          <select id=\"sel_mail\">\r\n");
      out.write("            <option value=\"\">메일선택</option>\r\n");
      out.write("            <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("            <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("            <option value=\"gmail.com\">gmail.com</option>           \r\n");
      out.write("          </select> \r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>  \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th colspan=\"2\" align=\"center\">\r\n");
      out.write("          <a href=\"javascript:join.submit()\"\r\n");
      out.write("              id=\"submit\">회원가입</a> &nbsp;\r\n");
      out.write("          <a href=\"javascript:join.reset()\"\r\n");
      out.write("              id=\"reset\" >다시작성</a>\r\n");
      out.write("         </th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>  \r\n");
      out.write("   </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
