/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-01-24 02:13:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.descartes.writing;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writing_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/descartes/writing/../include/footer.jsp", Long.valueOf(1485223977071L));
    _jspx_dependants.put("/descartes/writing/../include/header.jsp", Long.valueOf(1485223977072L));
    _jspx_dependants.put("/descartes/writing/../include/article_writing.jsp", Long.valueOf(1485223977070L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- writing/writing_list.jsp -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>데카르트</title>\r\n");
      out.write("<link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write(" <script>\r\n");
      out.write(" function login_window(){ // 사용자 정의 함수\r\n");
      out.write("\t  window.open(\"../login/login_form.jsp\",\"로그인\",\r\n");
      out.write("\t\t\t     \"width=380px, height=250px\");\r\n");
      out.write("     // open(\"파일명\", \"창이름\", \"폭/넓이\");\r\n");
      out.write(" }\r\n");
      out.write(" function member(){\r\n");
      out.write("\t  window.open(\"../member/member_form.jsp\",\"회원가입\",\r\n");
      out.write("\t\t\t  \"width=380px, height=250px\");\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">   <!-- 문서 영역 분류 -->\r\n");
      out.write("    <header> <!-- 머리말 영역 -->\r\n");
      out.write("        <div id=\"login\"> \r\n");
      out.write("           <a href=\"");
      out.print(request.getContextPath() );
      out.write("/descartes/index.jsp\">홈</a> | \r\n");
      out.write("           <a href=\"#\" onclick=\"login_window()\">로그인</a> | \r\n");
      out.write("           <a href=\"#\" onclick=\"member()\">회원가입</a>\r\n");
      out.write("        </div>       \r\n");
      out.write("       <hgroup>  <!-- 제목과 부제목을 그룹으로 묶어준다. -->\r\n");
      out.write("         <h1>데카르트, 서양 근대철학의 창시자</h1>\r\n");
      out.write("         <h2>Rene Descartes, 1596~1650</h2>\r\n");
      out.write("       </hgroup>\r\n");
      out.write("    </header> \r\n");
      out.write("    <nav class=\"nav\"> <!-- 네비게이션 영역 -->\r\n");
      out.write("\t   <ul> <!-- 순서 없는 목록 -->\r\n");
      out.write("         <li> <a href=\"../birth/birth_list.jsp\"> 탄 생</a></li>\r\n");
      out.write("         <li> <a href=\"../writing/writing_list.jsp\"> 저 서</a> </li>\r\n");
      out.write("         <li> <a href=\"../philosophy/philosophy_list.jsp\"> 철 학</a> </li>\r\n");
      out.write("         <li> <a href=\"../saying/saying_list.jsp\"> 명 언</a> </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>");
      out.write("\r\n");
      out.write("<!-- 변경 -->\r\n");
      out.write("\r\n");
      out.write("<section class=\"content\"> <!-- 문서의 절 : 여러 개 사용-->\r\n");
      out.write("    <h2>데카르트 저서</h2>  <!-- 절 제목 -->   \r\n");
      out.write("     <article> <!-- 본문 -->\r\n");
      out.write("     <h3> 근대의 출발점, 근대 철학의 아버지로 평가받는 데카르트는 종교 전쟁의 시대를 살면서 </h3>\r\n");
      out.write("     <table width=\"700\">\r\n");
      out.write("       <tr> \r\n");
      out.write("         <td> <img src=\"../images/book.jpg\"></td>\r\n");
      out.write("         <td> \r\n");
      out.write("         <p> 철학 대 신학,구교 대 신교, 구교 내 개혁과 보수로 대립하던          \r\n");
      out.write("     사상의 전선을 마주했다. 이성 없는 신앙은 광기와 살육으로 이어진다는 시대의 \r\n");
      out.write("     교훈 앞에서 그는 이성에 기초한 소통의 단초를 찾기 위해 인간 내면을 성찰했다. \r\n");
      out.write("     모든 것에 대한 의심에서 출발해 더 이상 의심할 수 없는 학문의 토대를 발견하고, \r\n");
      out.write("     다시 그 모든 것을 의심에서 해방시키는 정신의 자기 성찰 과정은, '생각하는 자아'를 \r\n");
      out.write("     철학의 제일원리이자 근대적 주체로서 발견하는 철학의 혁신과정이기도 하다.\r\n");
      out.write("     이로써 철학적 주제들은 새롭게 정비되었고, 방법론적 측면에서는 누구도 그 이전으로\r\n");
      out.write("     돌아갈 수 없게 하는 사유의 혁명이 이루어졌다. '성찰'은 현실의 문제를 근원적으로 \r\n");
      out.write("     묻고 따지는 사유의 방식이자 고립된 주체 간의 소통의 길을 모색하는 철학의 근본 행위이다. \r\n");
      out.write("     이책은 바로 이러한 과정과 결실을 보여준다.</p>\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("     </table>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"picture\"><img src=\"../images/bg2.png\" width=\"680\" height=\"195\" \r\n");
      out.write("     alt=\"오른쪽 탁자에 있는 여왕의 오른쪽 인물이 데카르트\"></div>      \r\n");
      out.write("  </article>\r\n");
      out.write("</section>\r\n");
      out.write("  <aside class=\"sidebar\"> <!-- 문서 보조내용(알림,광고,링크 등)-->\r\n");
      out.write("    <h3 align=\"center\">◐ 저서 구입 ◑</h3>\r\n");
      out.write("    <p>저서 구입을 원하는 분은 전화 010-1234-5678로\r\n");
      out.write("         연락주시기 바랍니다. </p>\r\n");
      out.write("    <img src=\"../images/book1.png\" width=\"130\" height=\"160\">\r\n");
      out.write("    <img src=\"../images/book2.png\" width=\"130\" height=\"160\">    \r\n");
      out.write("  </aside>  ");
      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  <footer> <!-- 꼬리말 -->\r\n");
      out.write("    <p>글 : 표정훈 / 저술가, 번역가 </p>  \r\n");
      out.write("    <address>E-mail : author@naver.com</address> <!-- e-mail 주소 -->\r\n");
      out.write("    <p> Copyright ⓒ. All rights reserved.</p>      \r\n");
      out.write("  </footer>      \r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
